Iter5
Galionme/metric-service pull request #6
Opened 2024-03-13 13:19 UTC by Galionme

2024-03-13 15:00 UTC, arttet requested changes

2024-03-13 15:00 UTC, arttet commented on cmd/agent/main.go
> +	"github.com/Galionme/metric-service.git/internal/agent"
CHANGE REQUEST: please sort imports

https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package

2024-03-13 15:00 UTC, arttet commented on cmd/agent/options/options.go
> +	OptionsAgent *Options
CHANGE REQUEST: please don't use global variables

2024-03-13 15:00 UTC, arttet commented on internal/agent/picker/picker.go
> +type Picker struct {
CHANGE REQUEST: please add a doc comment

2024-03-13 15:00 UTC, arttet commented on internal/handlers/home.go
> +  <!DOCTYPE html>
CHANGE REQUEST: it should be in a template file.

2024-03-13 15:00 UTC, arttet commented on internal/handlers/value.go
> +	case "counter":
CHANGE REQUEST: this is a magic string

2024-03-13 15:00 UTC, arttet commented on internal/middleware/correctness.go
> +func CorrectnessType(handler http.Handler) http.Handler {
CHANGE REQUEST: it should be a method

2024-03-13 15:00 UTC, arttet commented on internal/storage/memStorage.go
> +func init() {
CHANGE REQUEST: please don't use `init`

2024-03-13 15:00 UTC, arttet commented
Please add the following actions in CI:
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- https://golangci-lint.run/usage/install/#ci-installation

2024-03-18 14:09 UTC, arttet requested changes

2024-03-18 14:09 UTC, arttet commented on cmd/agent/main.go
> +	"github.com/Galionme/metric-service/internal/agent"
CHANGE REQUEST: please sort your imports

https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package

2024-03-18 14:09 UTC, arttet commented on cmd/agent/main.go
> +		panic(err)
CHANGE REQUEST: please don't use `panic`.

2024-03-18 14:09 UTC, arttet commented on cmd/agent/main.go
> +	if cfg.Address != "" && *options.Address != "" {
SUGGESTION: it would be better if it's in `flags.go`

2024-03-18 14:09 UTC, arttet commented on cmd/agent/main.go
> +		Post("http://" + address + "/update/" + typeMetric + "/" + nameMetric + "/" + valueMetric)
SUGGESTION: please use `fmt.Sprint`

2024-03-18 14:09 UTC, arttet commented on internal/handlers/update.go
> +		tmp, _ := storage.GlobalMemStorage.Get(nameMetric)
CHANGE REQUEST: please don't use global variables

2024-03-19 14:11 UTC, Galionme commented on internal/handlers/update.go
> +		tmp, _ := storage.GlobalMemStorage.Get(nameMetric)
Я же правильно понял что нужно сделать реализовать сервис?

2024-03-19 17:01 UTC, arttet requested changes

2024-03-19 17:01 UTC, arttet commented on internal/handlers/update.go
> +		tmp, _ := storage.GlobalMemStorage.Get(nameMetric)
You should initialize this service in the entry point.

2024-04-01 15:51 UTC, merged